on: [push, pull_request]
name: test and build
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v4'

      - uses: 'actions/setup-go@v5'
        with:
          go-version-file: 'go.mod'

      - run: make ci-tidy

      - run: make staticcheck

      - run: make test